# Generated by Django 2.2.7 on 2019-11-05 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_from', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cs_name', models.CharField(default='de_', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestof', models.IntegerField(choices=[(1, 'BO1'), (2, 'BO2'), (3, 'BO3'), (5, 'BO5')])),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_a_set', to='csgomatches.Lineup')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_b_set', to='csgomatches.Lineup')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(max_length=255)),
                ('ingane_name', models.CharField(max_length=255)),
                ('ingame_name_long', models.CharField(blank=True, max_length=255, null=True)),
                ('real_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_long', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MatchMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds_won_team_a', models.IntegerField(default=0)),
                ('rounds_won_team_b', models.IntegerField(default=0)),
                ('starting_at', models.DateTimeField()),
                ('delay_minutes', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgomatches.Match')),
                ('played_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgomatches.Map')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgomatches.Tournament'),
        ),
        migrations.CreateModel(
            name='LineupPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgomatches.Lineup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgomatches.Player')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgomatches.PlayerRole')),
            ],
        ),
        migrations.AddField(
            model_name='lineup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgomatches.Team'),
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caster', models.CharField(max_length=255)),
                ('stream_url', models.URLField()),
                ('vod_url', models.URLField(blank=True, null=True)),
                ('matchmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgomatches.MatchMap')),
            ],
        ),
    ]
