# Generated by Django 2.2.7 on 2019-11-05 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='ingane_name',
            new_name='ingame_name',
        ),
    ]
