# Generated by Django 2.2.7 on 2019-11-05 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0002_auto_20191105_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team_a',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_b',
        ),
        migrations.AddField(
            model_name='match',
            name='lineup_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_lineup_a_set', to='csgomatches.Lineup'),
        ),
        migrations.AddField(
            model_name='match',
            name='lineup_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_lineup_b_set', to='csgomatches.Lineup'),
        ),
    ]
