# Generated by Django 2.2.7 on 2019-11-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0003_auto_20191105_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='first_map_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
