# Generated by Django 2.2.7 on 2019-11-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0004_match_first_map_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='team_logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
