# Generated by Django 2.2.7 on 2019-11-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0006_auto_20191105_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='name_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
