# Generated by Django 2.2.7 on 2019-11-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0007_tournament_name_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmap',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchmap',
            name='map_nr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchmap',
            name='unplayed',
            field=models.BooleanField(default=False),
        ),
    ]
