# Generated by Django 2.2.7 on 2019-11-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0010_auto_20191106_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineup',
            options={'ordering': ['team__name', '-active_from']},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-first_map_at']},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['name']},
        ),
    ]
