# Generated by Django 2.2.7 on 2019-11-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0011_auto_20191106_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchmap',
            options={'ordering': ['-starting_at']},
        ),
    ]
