# Generated by Django 2.2.7 on 2019-11-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0012_auto_20191109_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchmap',
            options={'ordering': ['starting_at']},
        ),
    ]
