# Generated by Django 2.2.7 on 2019-11-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0014_auto_20191109_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externallink',
            options={'ordering': ['match', 'link_type']},
        ),
        migrations.AlterField(
            model_name='externallink',
            name='link_type',
            field=models.CharField(choices=[('hltv_match', 'HLTV'), ('99dmg_match', '99DMG'), ('twitch_cast', 'Cast'), ('twitch_vod', 'VOD'), ('youtube_vod', 'VOD')], max_length=255),
        ),
    ]
