# Generated by Django 2.2.7 on 2019-11-13 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('csgomatches', '0015_auto_20191109_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSGOSiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_team_settings', to='csgomatches.Team')),
                ('second_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec_team_settings', to='csgomatches.Team')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'unique_together': {('site', 'main_team', 'second_team')},
            },
        ),
    ]
