# Generated by Django 2.2.7 on 2019-11-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0016_csgositesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallink',
            name='link_flag',
            field=models.CharField(default='en', max_length=3),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='link_type',
            field=models.CharField(choices=[('hltv_match', 'HLTV'), ('hltv_demo', 'Demo'), ('99dmg_match', '99DMG'), ('twitch_cast', 'Cast'), ('twitch_vod', 'VOD'), ('youtube_vod', 'VOD')], max_length=255),
        ),
    ]
