# Generated by Django 2.2.7 on 2019-11-14 10:25

from django.db import migrations

def reflag_links_forw(apps, schema_editor):
    el_mdl = apps.get_model('csgomatches.ExternalLink')
    db_alias = schema_editor.connection.alias
    el_mdl.objects.using(db_alias).filter(link_type='99dmg_match').update(link_flag='de')
    el_mdl.objects.using(db_alias).filter(link_type='hltv_demo').update(link_flag='eu')

def reflag_links_reverse(apps, schema_editor):
    el_mdl = apps.get_model('csgomatches.ExternalLink')
    db_alias = schema_editor.connection.alias
    el_mdl.objects.using(db_alias).filter(link_type='99dmg_match').update(link_flag='en')
    el_mdl.objects.using(db_alias).filter(link_type='hltv_demo').update(link_flag='eu')


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0017_auto_20191114_1109'),
    ]

    operations = [
        migrations.RunPython(reflag_links_forw, reflag_links_reverse)
    ]
