# Generated by Django 2.2.7 on 2019-11-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0018_auto_20191114_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externallink',
            options={'ordering': ['match', 'link_flag', 'link_type']},
        ),
    ]
