# Generated by Django 2.2.7 on 2019-11-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0019_auto_20191114_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
