# Generated by Django 2.2.7 on 2019-11-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0020_team_name_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='cancelled',
            field=models.IntegerField(choices=[(0, 'normal'), (1, 'Defwin in favour of team A'), (2, 'Defwin in favour of team B')], default=0),
        ),
    ]
