# Generated by Django 2.2.7 on 2019-11-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0023_auto_20191122_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='hltv_match_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
