# Generated by Django 2.2.7 on 2019-11-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0024_auto_20191122_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='hltv_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
