# Generated by Django 2.2.7 on 2019-11-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0025_team_hltv_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='lineup',
            unique_together={('team', 'active_from')},
        ),
    ]
