# Generated by Django 2.2.7 on 2019-11-25 11:26

from django.db import migrations
from django.utils import timezone


def fix_lineup_active(apps, schema_editor):
    Lineup = apps.get_model('csgomatches.Lineup')
    for lu in Lineup.objects.all():
        lu.is_active = True
        lu.active_from = timezone.now().replace(year=2015, month=10, day=1, microsecond=0, minute=0, hour=0, )
        lu.save()


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0026_auto_20191124_1439'),
    ]

    operations = [
        migrations.RunPython(fix_lineup_active)
    ]
