# Generated by Django 2.2.7 on 2019-11-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0027_auto_20191125_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='real_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ingame_name_long',
        ),
        migrations.AddField(
            model_name='player',
            name='hltv_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='steam_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
