# Generated by Django 2.2.7 on 2019-11-25 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0028_auto_20191125_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineupplayer',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csgomatches.PlayerRole'),
        ),
    ]
