# Generated by Django 2.2.7 on 2019-12-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0030_staticpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='description',
            field=models.TextField(blank=True, help_text='Text is urlized', null=True),
        ),
    ]
