# Generated by Django 2.2.7 on 2020-01-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0033_auto_20200108_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='enable_tweet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='esea_bracket_match_ids',
            field=models.CharField(blank=True, help_text='Comma separated', max_length=20, null=True),
        ),
    ]
