# Generated by Django 2.2.7 on 2020-01-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0034_auto_20200108_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='last_tweet_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
