# Generated by Django 2.2.7 on 2020-01-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0036_auto_20200127_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='enable_html',
            new_name='enable_hltv',
        ),
    ]
