# Generated by Django 2.2.7 on 2020-01-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0037_auto_20200127_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='esea_bracket_match_ids',
        ),
        migrations.AddField(
            model_name='match',
            name='esea_match_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='esea_bracket_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
