# Generated by Django 2.2.7 on 2020-01-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0038_auto_20200127_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='esea_bracket_team_ids',
            field=models.CharField(blank=True, help_text='Comma Separated', max_length=255, null=True),
        ),
    ]
