# Generated by Django 2.2.7 on 2020-01-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0039_tournament_esea_bracket_team_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='esea_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='esea_team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
