# Generated by Django 2.2.7 on 2020-02-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0040_auto_20200131_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='esea_match_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
