# Generated by Django 2.2.7 on 2024-07-27 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0042_auto_20240727_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csgomatches.Game'),
        ),
    ]
