# Generated by Django 2.2.7 on 2024-07-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0043_lineup_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='game',
        ),
    ]
