# Generated by Django 5.1 on 2024-09-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0046_rename_team_logo_url_game_game_logo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csgositesetting',
            name='site_teams',
            field=models.ManyToManyField(to='csgomatches.team'),
        ),
    ]
