# Generated by Django 5.1 on 2024-09-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0047_alter_csgositesetting_site_teams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-first_map_at'], 'verbose_name_plural': 'matches'},
        ),
    ]
