# Generated by Django 5.1.1 on 2025-03-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0048_alter_match_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='enable_tweet',
            field=models.BooleanField(default=False),
        ),
    ]
