# Generated by Django 5.1 on 2024-09-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0048_alter_match_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='CsPlayer',
        ),
    ]
