# Generated by Django 5.1 on 2025-09-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0048_alter_match_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='block_voice_channel',
            field=models.CharField(blank=True, choices=[('VC Public Viewing 1', 'Public Viewing 1'), ('VC Public Viewing 2', 'Public Viewing 2')], max_length=100, null=True),
        ),
    ]
