# Generated by Django 5.1 on 2025-09-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0049_match_block_voice_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmap',
            name='map_pick_of_team',
            field=models.IntegerField(choices=[(1, 'Team A'), (2, 'Team B')], default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='block_voice_channel',
            field=models.CharField(blank=True, choices=[('VC 1', 'VC: Public Viewing 1'), ('VC 2', 'VC: Public Viewing 2')], max_length=100, null=True),
        ),
    ]
