# Generated by Django 5.1 on 2024-09-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0049_rename_player_csplayer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='CsMatch',
        ),
        migrations.RenameModel(
            old_name='Tournament',
            new_name='CsTournament',
        ),
    ]
