# Generated by Django 5.1.1 on 2025-03-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0049_alter_match_enable_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmap',
            name='map_nr',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
