# Generated by Django 5.1.1 on 2025-03-30 13:05

from django.db import migrations, models

def set_map_nr_to_default(apps, schema_editor):
    MatchMap = apps.get_model('csgomatches', 'MatchMap')
    MatchMap.objects.filter(map_nr__isnull=True).update(map_nr=1)

class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0049_alter_match_enable_tweet'),
    ]

    operations = [
        migrations.RunPython(set_map_nr_to_default),
        migrations.AlterField(
            model_name='matchmap',
            name='map_nr',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
