# Generated by Django 5.1.1 on 2025-03-30 13:18

from django.db import migrations, models

def set_default_map_nr(apps, schema_editor):
    MatchMap = apps.get_model('csgomatches', 'MatchMap')
    MatchMap.objects.filter(map_nr__isnull=True).update(map_nr=1)

class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0050_alter_matchmap_map_nr'),
    ]

    operations = [
        migrations.RunPython(set_default_map_nr),
        migrations.AlterField(
            model_name='matchmap',
            name='map_nr',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
