# Generated by Django 5.1 on 2024-09-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0050_rename_match_csmatch_rename_tournament_cstournament'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CSGOSiteSetting',
            new_name='SiteSetting',
        ),
    ]
