# Generated by Django 5.1.1 on 2025-03-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0050_alter_matchmap_map_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmap',
            name='map_nr',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
