# Generated by Django 5.1 on 2025-09-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0050_matchmap_map_pick_of_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmap',
            name='map_pick_of_team',
            field=models.IntegerField(choices=[(0, 'Decider'), (1, 'Team A'), (2, 'Team B')], default=0),
        ),
    ]
