# Generated by Django 5.1 on 2024-09-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0051_rename_csgositesetting_sitesetting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineupPlayer',
            new_name='CsLineupPlayer',
        ),
    ]
