# Generated by Django 5.1 on 2024-09-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0052_rename_lineupplayer_cslineupplayer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cslineupplayer',
            options={'verbose_name': 'CS Lineup Player', 'verbose_name_plural': 'CS Lineup Players'},
        ),
        migrations.AlterModelOptions(
            name='csmatch',
            options={'verbose_name': 'CS Match', 'verbose_name_plural': 'CS Matches'},
        ),
        migrations.AlterModelOptions(
            name='csplayer',
            options={'verbose_name': 'CS Player', 'verbose_name_plural': 'CS Players'},
        ),
        migrations.AlterModelOptions(
            name='cstournament',
            options={'verbose_name': 'CS Tournament', 'verbose_name_plural': 'CS Tournaments'},
        ),
    ]
