# Generated by Django 5.1 on 2024-09-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0053_alter_cslineupplayer_options_alter_csmatch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cslineupplayer',
            name='role',
            field=models.CharField(blank=True, choices=[('RIFLE', 'rifle'), ('IGL_RIFLE', 'igl_rifle'), ('AWP', 'awp'), ('IGL_AWP', 'igl_awp')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='PlayerRole',
        ),
    ]
