# Generated by Django 5.1.1 on 2025-04-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0053_simplematchmap_simplewincondition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basewincondition',
            name='name',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
