# Generated by Django 5.1.1 on 2025-10-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0054_alter_basewincondition_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csmatch',
            options={'verbose_name': 'CS Match', 'verbose_name_plural': 'CS Matches'},
        ),
    ]
