# Generated by Django 5.1 on 2024-09-29 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0054_alter_cslineupplayer_role_delete_playerrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csmatch',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_set', to='csgomatches.cstournament'),
        ),
    ]
