# Generated by Django 5.1 on 2024-09-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0055_alter_csmatch_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='cs_name',
        ),
    ]
