# Generated by GitHub Copilot on 2025-10-05

from django.db import migrations
from django.utils.text import slugify


def migrate_team_to_organization(apps, schema_editor):
    Team = apps.get_model('csgomatches', 'Team')
    Organization = apps.get_model('csgomatches', 'Organization')

    slug_field = Organization._meta.get_field('slug')
    max_length = getattr(slug_field, 'max_length', None) or 50

    existing_slugs = {
        slug for slug in Organization.objects.values_list('slug', flat=True) if slug
    }

    def build_base_slug(team):
        candidates = [team.name, team.name_long, team.name_alt]
        for candidate in candidates:
            if candidate:
                base_slug = slugify(candidate)
                if base_slug:
                    break
        else:
            base_slug = ''

        fallback = slugify(f"team-{team.pk}") or f"team-{team.pk}"
        if not base_slug:
            base_slug = fallback

        if base_slug and len(base_slug) > max_length:
            base_slug = base_slug[:max_length]
        if not base_slug:
            base_slug = fallback[:max_length]
        if not base_slug:
            base_slug = str(team.pk)[:max_length]
        if not base_slug:
            base_slug = 'team'
        return base_slug, fallback

    def ensure_unique_slug(base_slug: str, fallback: str, team_pk: int) -> str:
        slug = base_slug
        counter = 1
        while slug in existing_slugs or not slug:
            suffix = f"-{counter}"
            counter += 1
            if max_length and len(suffix) >= max_length:
                slug = (fallback or f"team-{team_pk}")[:max_length]
                continue

            available = max_length - len(suffix)
            if available <= 0:
                trimmed = (fallback or f"team-{team_pk}")[:max_length]
                slug = trimmed if trimmed else f"team-{team_pk}"[:max_length]
                continue

            trimmed_base = base_slug[:available]
            if not trimmed_base:
                trimmed_base = fallback[:available] if fallback else ''
            if not trimmed_base:
                trimmed_base = f"team-{team_pk}"[:available]
            slug = f"{trimmed_base}{suffix}"

        existing_slugs.add(slug)
        return slug

    for team in Team.objects.all().order_by('pk'):
        # Try to reuse existing organizations by matching names
        existing_org = Organization.objects.filter(name__iexact=team.name).first()
        if not existing_org and team.name_long:
            existing_org = Organization.objects.filter(name__iexact=team.name_long).first()
        if not existing_org and team.name_alt:
            existing_org = Organization.objects.filter(name__iexact=team.name_alt).first()

        if existing_org:
            updated = False
            if team.name_long and not existing_org.name_long:
                existing_org.name_long = team.name_long
                updated = True
            if updated:
                existing_org.save(update_fields=['name_long'])
            continue

        base_slug, fallback_slug = build_base_slug(team)
        slug = ensure_unique_slug(base_slug, fallback_slug, team.pk)
        name_long = team.name_long or team.name

        Organization.objects.create(
            name=team.name,
            name_long=name_long,
            slug=slug,
        )
    # Intentionally no return value: RunPython ignores it, and we want the migration to be idempotent.


def noop_reverse(apps, schema_editor):
    """No reverse migration: we don't want to delete created organizations automatically."""
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0055_alter_csmatch_options'),
    ]

    operations = [
        migrations.RunPython(migrate_team_to_organization, noop_reverse),
    ]
