# Generated by Django 5.1 on 2024-09-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0056_remove_map_cs_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchMap',
            new_name='CsMatchMap',
        ),
    ]
