# Generated by Django 5.1.1 on 2025-10-05 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0056_migrate_team_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseparticipant',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='csgomatches.organization'),
        ),
    ]
