# Generated by Django 5.1 on 2024-09-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0057_rename_matchmap_csmatchmap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csmatchmap',
            options={'verbose_name': 'CS Match Map', 'verbose_name_plural': 'CS Match Maps'},
        ),
    ]
