# Generated by Django 5.1 on 2024-09-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0058_alter_csmatchmap_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Map',
            new_name='CsMap',
        ),
        migrations.AlterModelOptions(
            name='csmap',
            options={'verbose_name': 'CS Map', 'verbose_name_plural': 'CS Maps'},
        ),
    ]
