# Generated by Django 5.1 on 2024-09-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0059_rename_map_csmap_alter_csmap_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csmatchmap',
            name='delay_minutes',
        ),
    ]
