# Generated by Django 5.1 on 2024-09-29 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0060_remove_csmatchmap_delay_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csmatchmap',
            old_name='played_map',
            new_name='map',
        ),
    ]
