# Generated by Django 5.1 on 2024-09-29 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0061_rename_played_map_csmatchmap_map'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lineup',
            new_name='CsLineup',
        ),
        migrations.AlterModelOptions(
            name='cslineup',
            options={'ordering': ['team__name', '-active_from'], 'verbose_name': 'CS Lineup', 'verbose_name_plural': 'CS Lineups'},
        ),
    ]
