# Generated by Django 5.1 on 2024-09-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0062_rename_lineup_cslineup_alter_cslineup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csmatch',
            options={'ordering': ['-first_map_at'], 'verbose_name': 'CS Match', 'verbose_name_plural': 'CS Matches'},
        ),
        migrations.AlterModelOptions(
            name='csmatchmap',
            options={'ordering': ['starting_at'], 'verbose_name': 'CS Match Map', 'verbose_name_plural': 'CS Match Maps'},
        ),
        migrations.AlterModelOptions(
            name='cstournament',
            options={'ordering': ['name'], 'verbose_name': 'CS Tournament', 'verbose_name_plural': 'CS Tournaments'},
        ),
    ]
