# Generated by Django 5.1 on 2024-12-02 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0063_alter_csmatch_options_alter_csmatchmap_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csmatchmap',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchmap_set', to='csgomatches.csmatch'),
        ),
    ]
