# Generated by Django 5.1 on 2024-12-02 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgomatches', '0064_alter_csmatchmap_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cslineup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_set', to='csgomatches.team'),
        ),
    ]
